# Generated by Django 5.2.6 on 2025-09-25 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='タスク詳細'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='error_detail',
            field=models.TextField(blank=True, verbose_name='エラー詳細'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='error_rows',
            field=models.IntegerField(default=0, verbose_name='エラー行数'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='success_rows',
            field=models.IntegerField(default=0, verbose_name='成功行数'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='total_rows',
            field=models.IntegerField(default=0, verbose_name='総行数'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時'),
        ),
        migrations.AlterField(
            model_name='taskcsvimportlog',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー名'),
        ),
    ]
